give @s pe:fireresistancepill
give @s pe:heroofthevillagepill
give @s pe:resistancepill
give @s pe:regenerationpill
give @s pe:waterbreathingpill
give @s pe:invisibilitypill
give @s pe:nightandvillagepill
give @s pe:strenightpill
give @s pe:speederationpill
give @s pe:strenstance
give @s pe:strenght
give @s pe:waterandfire
give @s pe:waterresistancepill
give @s pe:speedpill
give @s pe:nightvisionpill
give @s pe:slowfallingpill
give @s pe:levitationpill
give @s pe:levitationfallingpill
give @s pe:invisiblefirepill
give @s pe:speedibility
give @s pe:heroofregenerationpill
