give @s gf:redstoneflower
give @s gf:diamondflower
give @s gf:emeraldflower
give @s gf:goldenflower
give @s gf:ironflower
give @s gf:coalflower
give @s gf:sworddiamondflower
give @s gf:swordemeraldflower
give @s gf:swordironflower
give @s gf:swordcoalflower
give @s gf:swordgoldenflower
give @s gf:swordredstoneflower
give @s gf:redstonenugget
give @s gf:diamondnugget
give @s gf:emeraldnugget
give @s gf:coalnugget
give @s gf:goldenpotion
give @s gf:emeraldpotion
give @s gf:diamondpotion
give @s gf:coalpotion
give @s gf:redstonepotion
give @s gf:goldenplant
give @s gf:ironpotion
give @s gf:coalplant
give @s gf:redstoneplant
give @s gf:diamondplant
give @s gf:ironplant
give @s gf:emeraldplant
