give @s mp:emeraldpiecethree
give @s mp:diamondpieceone
give @s mp:emeraldpiecetwo
give @s mp:emeraldpiecefour
give @s mp:diamondpiecetwo
give @s mp:emeraldpieceone
give @s mp:diamondpiecethree
give @s mp:diamondpiecefour
give @s mp:goldenpiecetwo
give @s mp:goldenpiecethree
give @s mp:goldenpiecefour
give @s mp:ironpieceone
give @s mp:ironpiecetwo
give @s mp:goldenpieceone
give @s mp:redstonepieceone
give @s mp:redstonepiecefour
give @s mp:redstonepiecethree
give @s mp:ironpiecefour
give @s mp:redstonepiecetwo
give @s mp:ironpiecethree
