give @s pe:fireresistancepill
give @s pe:heroofthevillagepill
give @s pe:regenerationpill
give @s pe:resistancepill
give @s pe:waterbreathingpill
give @s pe:invisibilitypill
give @s pe:speedpill
give @s pe:strenstance
give @s pe:nightvisionpill
give @s pe:strenght
give @s pe:nightandvillagepill
give @s pe:strenightpill
give @s pe:speederationpill
give @s pe:waterresistancepill
give @s pe:waterandfire
give @s pe:invisiblefirepill
give @s pe:speedibility
give @s pe:heroofregenerationpill
give @s pe:slowfallingpill
give @s pe:levitationpill
give @s pe:levitationfallingpill
give @s pe:jumpfallingpill
give @s pe:removeeffectspill
give @s pe:jumpboostpill
give @s pe:basepillore
give @s pe:nightresistancepill
give @s pe:specialpillone
give @s pe:basepill
give @s pe:nightinvisibilitypill
give @s pe:jumpinvisibilitypill
