give @s ia:turtlehelmet
give @s ia:diamondhelmet
give @s ia:chainmailhelmet
give @s ia:goldenhelmet
give @s ia:ironhelmet
give @s ia:leatherhelmet
give @s ia:netheritehelmet
give @s ia:goldenchestplate
give @s ia:ironchestplate
give @s ia:netheritechestplate
give @s ia:chainmailchestplate
give @s ia:leatherchestplate
give @s ia:diamondboots
give @s ia:chainmailboots
give @s ia:goldenboots
give @s ia:ironboots
give @s ia:netheriteboots
give @s ia:leatherboots
give @s ia:chainmailleggings
give @s ia:diamondleggings
give @s ia:goldenleggings
give @s ia:ironleggings
give @s ia:leatherleggings
give @s ia:netheriteleggings
give @s ia:diamondchestplate
give @s ia:fgoldenore
give @s ia:fdiamondore
give @s ia:fironblock
give @s ia:fcoppeblock
give @s ia:fnetheriteblock
give @s ia:fchainmailblock
