give @s kf:onigiri
give @s kf:goldensoup
give @s kf:emeraldsoup
give @s kf:bittencookie
give @s kf:lapislazulisoup
give @s kf:diamondsoup
give @s kf:avocado
give @s kf:pinkbeet
give @s kf:chocolatebar
give @s kf:pittedavocado
give @s kf:diamondlollipop
give @s kf:eggs
give @s kf:redstonesoup
give @s kf:happyemojicookie
give @s kf:redstonepopsicle
give @s kf:emeraldlollipop
give @s kf:goldenlollipop
give @s kf:goldenpopsicle
give @s kf:chocolatepopsicle
give @s kf:diamondpopsicle
give @s kf:seaweedpopsicle
give @s kf:greentea
give @s kf:chocolatelollipop
give @s kf:seriousemojicookie
give @s kf:seaweedorigini
give @s kf:greencoconot
give @s kf:redstonelollipop
give @s kf:obsidianjuice
give @s kf:pear
give @s kf:diamondjuice
give @s kf:redstonejuice
give @s kf:redstonedrink
give @s kf:partofthecoconot
give @s kf:applejuice
give @s kf:coconot
give @s kf:diamonddrink
give @s kf:obsidiandrink
give @s kf:goldenjuice
