give @s fd:goldenpotato
give @s fd:goldenbread
give @s fd:goldenbeetroot
give @s fd:goldensweetberries
give @s fd:diamondapple
give @s fd:diamondcarrot
give @s fd:diamondmelonslice
give @s fd:diamondapples
give @s fd:diamondbeetroot
give @s fd:diamondbread
give @s fd:diamondsweetberries
give @s fd:ironmelon
give @s fd:ironapple
give @s fd:ironcarrot
give @s fd:ironpotato
give @s fd:ironbread
give @s fd:ironbeetroot
give @s fd:ironsweetberries
give @s fd:emeraldmelon
give @s fd:emeraldapple
give @s fd:emeraldpotato
give @s fd:emeraldcarrot
give @s fd:emeraldbread
give @s fd:emeraldbeetroot
give @s fd:emeraldsweetberries
give @s fd:redstonemelon
give @s fd:redstoneapple
give @s fd:redstonecarrot
give @s fd:redstonepotato
give @s fd:redstonebread
give @s fd:redstonebeetroot
give @s fd:redstonesweetberries
give @s fd:diamondpotato
give @s fd:copperapple
give @s fd:copperbread
give @s fd:coppermelon
give @s fd:coppersweetberries
give @s fd:copperpotato
give @s fd:coppercarrot
give @s fd:copperbeetroot
